#/*YAML is a human readable data serialization standard that can be used in conjunction with all programming
#  languages and is often used to write configuration files*/
#spring:
#  application:
#    name : student-service
#
#  datasource:
#    url : ${datasource.url}
#    username : ${datasource.username}
#    password : ${datasource.password}
#  jpa:
#    properties:
#      hibernate:
#        dialect: ${datasource.dialect}
#        connection:
#          characterEncoding: UTF-8
#          CharSet: UTF-8
#          useUnicode: true
#    show-sql: true
#    hibernate:
#      ddl-auto: none
